# Generated by Django 4.0.10 on 2023-04-04 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=800, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
