# Generated by Django 4.0.10 on 2023-04-08 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tg_user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Телеграм ID'),
            preserve_default=False,
        ),
    ]
