# Generated by Django 4.0.10 on 2023-04-09 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
