# Generated by Django 4.0.10 on 2023-04-10 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_order_buying_type_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_at',
            field=models.DateField(default=datetime.date(2023, 4, 10), verbose_name='Дата создания'),
        ),
    ]
