# Generated by Django 4.0.10 on 2023-04-17 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart_is_order_alter_customer_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('uz', 'uz')], default='en', max_length=5, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_at',
            field=models.DateField(default=datetime.date(2023, 4, 17), verbose_name='Дата создания'),
        ),
    ]
