# Generated by Django 4.0.10 on 2023-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_customer_lang_alter_customer_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('uz', 'uz')], default='ru', max_length=5, verbose_name='Язык'),
        ),
    ]
