# Generated by Django 4.0.10 on 2023-04-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500, verbose_name='URL')),
                ('params', models.CharField(blank=True, max_length=500, null=True, verbose_name='Доп параметры')),
                ('create_at', models.DateField(blank=True, null=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'reports',
            },
        ),
    ]
